### ISSUE TITLE
ByteBuffer's `setString`/`writeString` etc should support `StringProtocol`

### ISSUE THREAD

**Issue by helje5** [apple/swift-nio#1332]
The ByteBuffer String API is tied to the concrete `String` type. Would be nice to allow arbitrary `StringProtocol` values, most importantly substrings.

### SwiftNIO version/commit hash

2.12.0

### Swift & OS version (output of `swift --version && uname -a`)

5.1 any

**Comment by Lukasa** [comment]
From my racy issue in #1333: We should add new versions of these functions that take a generic StringProtocol. These must be inlinable, of course. Ideally we'd verify that calling the generic function with a String performs just as well as calling the String-specific one.

**Comment by ianpartridge** [comment]
I'm curious why the existing functions couldn't be made generic, rather than adding additional generic ones? Couldn't we use `@_specialize` to hint that `String` and `Substring` should be specialized?

**Comment by helje5** [comment]
Would it change the ABI?

**Comment by jckarter** [comment]
IMO `StringProtocol` is pretty silly. You could have the implementation take a `Substring` with an inlinable overload that takes a String and passes down `string[...]` automatically, maybe.

**Comment by helje5** [comment]
That doesn't really answer the question ;-)

But regardless, for APIs you essentially want to enable both always, and having to write everything twice is pretty silly too.
Personally I'd prefer to have just String, but that's besides the point here.

**Comment by jckarter** [comment]
Well, yes, changing a nongeneric function to a generic one is going to change the ABI, and `@_specialize` won't provide entry points ABI-compatible with the original concrete entry points.

I was just also saying that in general, making something generic over a protocol to cover two types, one of which has a nearly free conversion to the other, is going to add a lot of performance overhead. The whole String/Substring/StringProtocol thing is…not the way I'd have done things, but given the world we built, if the goal is to make something accept both `String` and `Substring`, it's much more practical to just take `Substring` IMO.

**Comment by helje5** [comment]
> making something generic over a protocol to cover two types, one of which has a nearly free conversion to the other, is going to add a lot of performance overhead
Even if it is `@inlinable`?

**Comment by jckarter** [comment]
If it's inlinable, the generic version still has to exist and take up space in case it doesn't get inlined.

**Comment by Lukasa** [comment]
So while @jckarter's idea is good, we certainly can't take that approach for any current Swift version, because `Substring` has no fast access to its backing storage: see [SR-11999](https://bugs.swift.org/browse/SR-11999).

With this in mind, we should consider adding a `Substring` entry point that we know is slow (just calls directly into the slow path), with the ability to speed it up in future, but the `String` entry point absolutely should _not_ call into the `Substring` one until that bug is fixed.

**Comment by helje5** [comment]
If it is expensive, I think we should probably leave it alone then. I was originally thinking that I'm going to expose the BB to the framework user, but I guess I just wrap. NIO should probably stick to just the base API it can do efficiently and not add convenience bloat.

**Comment by Davidde94** [comment]
Resolved in #1346

**Comment by weissi** [comment]
Well, the actual issue is not resolved but we added a version that takes `Substring`. I’m not sure if we should just close it. Let’s discuss if we really don’t want `StringProtocol`

**Comment by gmilos** [comment]
We now have support for `String` and `Substring`, this covers most of the use cases and it'd be risky to support other `StringProtocol`s since the performance might be subpar (and unexpected). Let's close until there is clear use case.
