### ISSUE TITLE
Archiving fails in Swift 5.9, Xcode 15 beta

### ISSUE THREAD

**Issue by codynhat** [apple/swift-nio#2511]
### Expected behavior
Archiving a project with swift-nio as a dependency should succeed in Swift 5.9

### Actual behavior
Archive fails with:
```
Sources/NIOEmbedded/AsyncTestingEventLoop.swift:59:20 
Type 'NIOAsyncTestingEventLoop' does not conform to protocol 'Executor'
```

### Steps to reproduce

1. Add `swift-nio` as SPM dependency
2. Archive target

### SwiftNIO version/commit hash

2.58.0

### System & version information

macOS 13.5
Xcode 15 beta 7
Targeting iOS 17

**Comment by Lukasa** [comment]
Thanks for this report! This is a known issue with Swift 5.9. The fix has been merged here: https://github.com/apple/swift/pull/67957

**Comment by bdkjones** [comment]
@Lukasa Came here to report this same issue. Is there a workaround until Xcode 15 beta 8 ships? My codebase has adopted features that make reverting to Xcode 14 a non-starter.

**Comment by Lukasa** [comment]
Yes, pin down to 2.57 until there is an Xcode release.

**Comment by codynhat** [comment]
I have not been able to get a workaround working. I've used version 2.57, which successfully creates a release build but crashes immediately upon launch. The same issue also still exists with Xcode 15 beta 8.

**Comment by bdkjones** [comment]
@codynhat - I can confirm that SwiftNIO 2.54.0 is unaffected. When I hit this snag, I just rolled back the package to the last version I had before updating. Building a release binary with the archive->notarization flow in Xcode 15 beta 7 worked fine.

**Comment by bdkjones** [comment]
The fact that the issue persists in Xcode 15 beta 8 is a bad sign. We're two weeks away from the iOS 17 launch, which means the window of time for Apple to actually fix nonsense in Xcode before the GM release is rapidly closing. If the GM build of Xcode 15 doesn't include the fix to Swift @Lukasa referenced above, anyone using SwiftNIO will be in a tight spot. Hopefully somebody on the team has strings to pull in Cupertino.

**Comment by aiden-leong** [comment]
I'd like to reuse this issue:

```
/SourcePackages/checkouts/swift-nio/Sources/NIOPosix/SelectableEventLoop.swift:37:22: error: type 'SelectableEventLoop' does not conform to protocol 'Executor'
internal final class SelectableEventLoop: EventLoop {
                     ^
_Concurrency.Executor:10:10: note: protocol requires function 'enqueue' with type 'ExecutorJob'; do you want to add a stub?
    func enqueue(_ job: consuming ExecutorJob)
         ^
```

macOS 14.0 (23A5337a)
Darwin 23.0.0

**Comment by Lukasa** [comment]
As noted above, this is an Xcode issue, not a macOS issue.

**Comment by codynhat** [comment]
I am able to get a release build to build by using an older version of SwiftNIO. However, the build always crashes on launch with `NO_CRASH_STACK`.

It also appears that the commit mentioned above https://github.com/apple/swift/pull/67957 is not merged into the `release/5.9` branch, but is only on `main`. This means the fix is not being included in the 5.9 development snapshots of Swift, which I assume is what is being included in the Xcode beta. Can anyone confirm this?

**Comment by Lukasa** [comment]
That is incorrect, it was backported in apple/swift#67959 and apple/swift#67960.

**Comment by codynhat** [comment]
> That is incorrect, it was backported in [apple/swift#67959](https://github.com/apple/swift/pull/67959) and [apple/swift#67960](https://github.com/apple/swift/pull/67960).

Ok, great! Thanks for the quick response. I will just wait until this gets included in Xcode.

**Comment by ktoso** [comment]
We're aware of the issue and looking into it.

**Comment by Lukasa** [comment]
Hey reporters, can I ask you to double-check with Xcode GM (15A240d) and confirm whether this still occurs for you?

**Comment by bdkjones** [comment]
**Mixed Results** with Xcode 15 (15A240d).

1) Archiving an app with swift-nio 2.58.0 and swift-nio-ssl 2.25.0 now completes without throwing an error.

2) I see build warnings that are new and appear related to Swift NIO:

<img width="740" alt="Screenshot 2023-09-19 at 23 15 39" src="https://github.com/apple/swift-nio/assets/926566/6c20d516-8dd0-42dd-b458-5db7dd095176">

**Comment by Lukasa** [comment]
Those are for swift-nio-ssl, can you file an issue on that repo and I'll take a look?

**Comment by bdkjones** [comment]
@Lukasa - sure thing. It would appear that *this* issue is fixed with Xcode 15 GM.

**Comment by Lukasa** [comment]
Fab, thanks folks. I'm going to close this out then, but please don't hesitate to comment here if for some reason this issue persists for you.

**Comment by aiden-leong** [comment]
> Those are for swift-nio-ssl, can you file an issue on that repo and I'll take a look?

![WX20230920-155329@2x](https://github.com/apple/swift-nio/assets/7299189/3469e5c8-7010-465b-a948-a77aeb460816)

`'Executor.enqueue(ExecutorJob)' will never be used, due to the presence of 'enqueue(UnownedJob)'`

Looks good to me.

**Comment by FranzBusch** [comment]
We are aware of those warnings and there is already a PR up in the Swift repo that fixes them: https://github.com/apple/swift/pull/68617
