### ISSUE TITLE
segfault after updating Xcode to version 16.0 beta 5

### ISSUE THREAD

**Issue by Th3F0x-code** [apple/swift-nio#2834]
### Expected behavior
program should run

### Actual behavior
Segmentation fault. Prior to updating Xcode to the beta 5 version, the application functioned correctly.

### If possible, minimal yet complete reproducer code (or URL to code)
the program crash at this point in the package 

<img width="1492" alt="Screenshot 2024-08-08 at 21 24 09" src="https://github.com/user-attachments/assets/cd70b2ba-bed9-4a6a-a3b6-db233d812906">

### SwiftNIO version/commit hash

hash : "4c4453b489cf76e6b3b0f300aba663eb78182fad",
version": "2.70.0"

### System & version information

MacOS 15.1 beta 1
Swift version swiftlang-6.0.0.7.6

**Comment by Lukasa** [comment]
Can you supply a full crash report? You can get it out of `Console.app`

**Comment by Lukasa** [comment]
Given where this crash is, I suspect this is actually an Xcode bug in Beta 5, but I'd like to confirm that.

**Comment by ajason** [comment]
I encountered the same issue, I'm not sure if this is the crash report you need?
[AuthVaporTestApp-2024-08-08-172527.txt](https://github.com/user-attachments/files/16554353/AuthVaporTestApp-2024-08-08-172527.txt)

**Comment by wvabrinskas** [comment]
I get the same issue in my project. Unrelated to Vapor. It’s specific to Xcode 16b5. It happens for me when I build to device that’s on iOS 18.1b1. However releasing to TestFlight and running it I don’t see the issue. Changing to `withUnsafeThrowingContinuation` solves the problem.

**Comment by vmanot** [comment]
Echoding @Th3F0x-code, @ajason and @wvabrinskas, I can confirm that I'm facing this issue as well on Xcode 16.0 beta 5.

**Comment by Th3F0x-code** [comment]
@Lukasa this log file?

[App-2024-08-08-211954.txt](https://github.com/user-attachments/files/16557502/App-2024-08-08-211954.txt)

**Comment by Lukasa** [comment]
This looks to me like a null pointer dereference in the Swift runtime, which is very probably an ABI mismatch. Can you please file a report using Feedback Assistant and post the number here?

**Comment by Th3F0x-code** [comment]
The report number is **FB14726471**

**Comment by wvabrinskas** [comment]
Looks like `withTaskGroup` also crashes... 
![image](https://github.com/user-attachments/assets/421b6138-c49c-409f-a178-6cb81986a121)
Same way

**Comment by jcbriones** [comment]
Same issue here

**Comment by Lukasa** [comment]
Hi folks, I believe this is a regression in the Xcode 15 Beta 5 release. It's not going to be all that effective to comment a +1 on this thread: please use Feedback Assistant to file reports.

**Comment by Th3F0x-code** [comment]
It seems to have been fixed with the release:  16.1 beta (16B5001e)

**Comment by Lukasa** [comment]
Fantastic. I'll leave this open until we have an Xcode 16.0 release that also contains a fix.

**Comment by wvabrinskas** [comment]
@Th3F0x-code from my testing it doesn't appear to have been FULLY fixed. It appears that there's a crash still related with `withTaskGroup`

**Comment by wvabrinskas** [comment]
Looks like `withTaskGroup` is fixed in B6

**Comment by Lukasa** [comment]
Fantastic. Thanks all!
